---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/danielebarbaro/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_home: "~"
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .gitconfig
  - .inputrc
  - .vimrc
  - .osx

homebrew_installed_packages:
  - autoconf
  - bash
  - bash-completion
  - ctop
  - htop
  - docker
  - docker-compose
  - docker-machine
  - docker-machine-driver-xhyve
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - php-cs-fixer
  - ssh-copy-id
  - tree
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - composer
  - curl
  - ffmpeg
  - gd
  - jpeg
  - redis
  - xdebug-osx
  - rename
  - mysql
  - libtiff
  - argon2
  - openjpeg
  - hugo
  - nginx
  - mosquitto
  - postgresql
  - phpunit
  - dnsmasq
  - httpd
  - supervisor

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - caskroom/cask
  - caskroom/versions/firefox-developer-edition
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - limechat
  - macvim
  - sequel-pro
  - skype
  - slack
  - spotify
  - sublime-text
  - transmit
  - vagrant
  - mysqlworkbench
  - phpstorm
  - postman
  - pycharm
  - vlc
  - whatsapp
  - telegram
  - rdm
  - ccleaner
  - teamviewer
  - filezilla
  - toggldesktop

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  - name: laravel/installer
  - name: drush/drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages:
  - name: mailcatcher
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
