---
# Create nginx config

- name: Create sites-available folder
  file:
    path: /usr/local/etc/nginx/sites-available
    state: directory
    mode: 0755
    group: admin

- name: Create sites-enabled folder
  file:
    path: /usr/local/etc/nginx/sites-enabled
    state: directory
    mode: 0755
    group: admin

- name: Create conf.d folder
  file:
    path: /usr/local/etc/nginx/conf.d
    state: directory
    mode: 0755
    group: admin

- name: Create ssl folder
  file:
    path: /usr/local/etc/nginx/ssl
    state: directory
    mode: 0755
    group: admin

- name: Copy configurations
  copy:
    src: /files/nginx/conf.d/
    dest: /usr/local/etc/nginx/conf.d/
    remote_src: yes
    directory_mode: yes

- name: Copy nginx.conf
  copy:
    src: /files/nginx/nginx.conf
    dest: /usr/local/etc/nginx/
    remote_src: yes
    group: admin

- name: Copy mime.types
  copy:
    src: /files/nginx/mime.types
    dest: /usr/local/etc/nginx/
    remote_src: yes
    group: admin
