---
# Custom Terminal theme.
- name: Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: no

- name: Ensure custom Terminal profile is added.
  shell: open files/terminal/dB.terminal
  changed_when: false
  when: "'dB' not in terminal_theme.stdout"

